server:
    port: 8081

app:
    security:
        jwt:
            jwks-uri: http://localhost:8080/.well-known/jwks.json
            issuer: bff-service
            audience: internal-api

logging:
    level:
        com.example.userservice: INFO
        org.springframework.security: INFO